/**
 * Shared Bangla (বাংলা) UI strings for Dawat RMG SOFT.
 * Centralised so every Commercial module page uses consistent labels.
 */
export const bn = {
  brand: "সেইম দাওয়াত আরএমজি ইআরপি",
  brandSub: "Order confirmation থেকে Shipment পর্যন্ত—সব এক ERP-তে।",

  // Generic actions
  add: "নতুন যোগ করুন",
  save: "সংরক্ষণ করুন",
  cancel: "বাতিল",
  edit: "সম্পাদনা",
  update: "আপডেট",
  view: "বিস্তারিত",
  delete: "মুছে ফেলুন",
  close: "বন্ধ করুন",
  search: "খুঁজুন",
  reset: "রিসেট",
  applyFilter: "ফিল্টার প্রয়োগ করুন",
  exportPdf: "PDF এক্সপোর্ট",
  exportExcel: "এক্সেল এক্সপোর্ট",
  actions: "কার্যক্রম",
  status: "অবস্থা",
  all: "সবগুলো",
  noData: "নির্বাচিত ফিল্টারের জন্য কোনো তথ্য পাওয়া যায়নি।",
  required: "আবশ্যক",
  loading: "লোড হচ্ছে...",
  totalRecords: "মোট রেকর্ড",
  details: "বিস্তারিত তথ্য",
  notes: "মন্তব্য",
  from: "থেকে",
  to: "পর্যন্ত",

  // Buyers module
  buyers: {
    heading: "ক্রেতা / বায়ার তালিকা",
    subtitle: "অর্ডার ও পেমেন্ট হিস্ট্রি",
    newBuyer: "নতুন ক্রেতা",
    name: "ক্রেতার নাম",
    company: "কোম্পানি",
    phone: "ফোন নম্বর",
    email: "ইমেইল",
    address: "ঠিকানা",
    searchPlaceholder: "নাম, কোম্পানি বা ফোন দিয়ে খুঁজুন...",
    totalOrders: "মোট অর্ডার",
    totalValue: "মোট মূল্য",
    totalDue: "মোট বকেয়া",
    totalReceived: "মোট গৃহীত",
    orderHistory: "অর্ডার হিস্ট্রি",
    paymentHistory: "পেমেন্ট হিস্ট্রি",
    selectBuyerHint: "বিস্তারিত দেখতে একজন ক্রেতা নির্বাচন করুন",
    noBuyers: "কোনো ক্রেতা পাওয়া যায়নি",
  },

  // Orders module
  orders: {
    heading: "Style / PO Orders",
    subtitle: "Export order tracking — buyer PO, style, quantity and lifecycle status",
    newOrder: "নতুন অর্ডার",
    searchOrder: "অর্ডার খুঁজুন",
    searchPlaceholder: "PO, buyer or style...",
    selectBuyer: "ক্রেতা নির্বাচন করুন",
    buyer: "ক্রেতা",
    po: "পিও নম্বর",
    style: "স্টাইল",
    product: "পণ্যের নাম",
    color: "রং",
    qty: "পরিমাণ (পিস)",
    unitPrice: "প্রতি পিস মূল্য",
    shipDate: "শিপমেন্ট তারিখ",
    stage: "উৎপাদন ধাপ",
    orderValue: "অর্ডার মূল্য",
    progress: "অগ্রগতি",
    taStatus: "টি&এ অবস্থা",
    paymentStatus: "পেমেন্ট অবস্থা",
  },

  // T&A Calendar module
  ta: {
    heading: "T&A Calendar",
    subtitle: "Time & Action — order-wise task timeline from confirmation to shipment",
    totalTasks: "মোট কাজ",
    delayed: "বিলম্বিত",
    inProgress: "চলমান",
    completed: "সম্পন্ন",
    tableView: "টেবিল ভিউ",
    timelineView: "টাইমলাইন ভিউ",
    highRiskOnly: "হাই রিস্ক শুধু",
    delayedOnly: "বিলম্বিত শুধু",
    todaysTasks: "আজকের কাজ",
    searchOrder: "অর্ডার খুঁজুন",
    searchPlaceholder: "PO, Style or Buyer name...",
    taskStatus: "কাজের অবস্থা",
    department: "বিভাগ",
    plannedFrom: "পরিকল্পিত তারিখ (থেকে)",
    plannedTo: "পরিকল্পিত তারিখ (পর্যন্ত)",
    riskLevel: "ঝুঁকির মাত্রা",
    taskName: "কাজের নাম",
    owner: "দায়িত্বপ্রাপ্ত",
    plannedDate: "পরিকল্পিত তারিখ",
    actualDate: "প্রকৃত তারিখ",
    updateStatus: "অবস্থা আপডেট করুন",
  },

  // Merchandising module
  merch: {
    heading: "Merchandising",
    subtitle: "Buyer communication, tech pack, sample approval and order lifecycle",
    orderTracking: "Order Tracking",
    sampleApproval: "Sample Approval",
    runningStyles: "চলমান স্টাইল",
    atRisk: "ঝুঁকিপূর্ণ",
    ppPending: "পিপি বাকি",
    techPackApproved: "টেক প্যাক অনুমোদিত",
    searchOrder: "অর্ডার খুঁজুন",
    searchPlaceholder: "PO, buyer, style...",
    riskLevel: "ঝুঁকির মাত্রা",
    fitSample: "ফিট স্যাম্পল",
    ppSample: "পিপি স্যাম্পল",
    productionApproval: "প্রোডাকশন অনুমোদন",
    techPackStatus: "টেক প্যাক অবস্থা",
  },

  // Costing module
  costing: {
    heading: "Costing & Consumption",
    subtitle: "Fabric consumption, trims, CM, washing/printing and profit margin per style",
    costedStyles: "কস্টিং করা স্টাইল",
    avgMargin: "গড় মার্জিন",
    selectStyle: "স্টাইল নির্বাচন করুন",
    searchCosting: "কস্টিং খুঁজুন",
    searchPlaceholder: "Buyer, style, fabric...",
    fabricDetails: "ফেব্রিক বিবরণ",
    fabricName: "ফেব্রিকের নাম",
    gsm: "জিএসএম",
    consumption: "কনজাম্পশন (গজ/পিস)",
    fabricCost: "ফেব্রিক খরচ",
    trimsCost: "ট্রিমস খরচ",
    cmCost: "সিএম খরচ",
    washCost: "ওয়াশ/প্রিন্ট খরচ",
    totalCost: "মোট খরচ",
    unitPrice: "প্রতি পিস মূল্য",
    margin: "মার্জিন",
    breakdown: "কস্ট ব্রেকডাউন",
  },

  // Procurement module
  procurement: {
    heading: "Procurement Management",
    subtitle: "Fabric & trims booking, supplier PO tracking and in-house status",
    fabricBooking: "ফেব্রিক বুকিং",
    trimsBooking: "ট্রিমস বুকিং",
    supplierPo: "সাপ্লায়ার পিও",
    inhouseStatus: "ইন-হাউজ অবস্থা",
    newBooking: "নতুন বুকিং",
    searchPlaceholder: "Supplier, item, PO or style...",
    supplier: "সাপ্লায়ার",
    item: "আইটেম",
    selectOrder: "অর্ডার নির্বাচন করুন",
    required: "প্রয়োজনীয় পরিমাণ",
    received: "প্রাপ্ত পরিমাণ",
    balance: "বাকি",
    expectedDate: "প্রত্যাশিত তারিখ",
    receivedDate: "প্রাপ্তির তারিখ",
    totalBookings: "মোট বুকিং",
    inHousePct: "ইন-হাউজ %",
    delayedBookings: "বিলম্বিত বুকিং",
    pendingBalance: "অবশিষ্ট পরিমাণ",
  },

  // Inventory module
  inventory: {
    heading: "Inventory Management",
    subtitle: "Fabric, trims & finished goods stock with full ledger tracking",
    fabricStock: "ফেব্রিক স্টক",
    trimsStock: "ট্রিমস স্টক",
    cuttingIssue: "কাটিং ইস্যু",
    finishedGoods: "ফিনিশড গুডস",
    stockLedger: "স্টক লেজার",
    newItem: "নতুন আইটেম",
    searchPlaceholder: "Item, PO, style or buyer...",
    itemName: "আইটেমের নাম",
    colorSpec: "রং / স্পেসিফিকেশন",
    location: "অবস্থান",
    received: "প্রাপ্ত",
    issued: "ইস্যুকৃত",
    balance: "ব্যালেন্স",
    totalBalance: "মোট ব্যালেন্স",
    lowStock: "কম স্টক আইটেম",
    totalItems: "মোট আইটেম",
  },

  // Production module
  production: {
    cutting: {
      heading: "Cutting Section",
      subtitle: "Fabric issue, cut quantity, rejection and running balance per order",
      fabricIssued: "ফেব্রিক ইস্যু",
      cutQty: "কাট পরিমাণ",
      reject: "রিজেক্ট",
      balance: "অবশিষ্ট",
      totalCut: "মোট কাটিং",
      totalReject: "মোট রিজেক্ট",
      inProgress: "চলমান",
      completed: "সম্পন্ন",
    },
    sewing: {
      heading: "Sewing Line Efficiency",
      subtitle: "Target vs output, defect rate and line-wise efficiency tracking",
      target: "টার্গেট",
      output: "আউটপুট",
      defect: "ত্রুটি",
      operators: "অপারেটর",
      efficiency: "দক্ষতা",
      avgEfficiency: "গড় দক্ষতা",
      totalOutput: "মোট আউটপুট",
      belowTarget: "টার্গেটের নিচে",
    },
    finishing: {
      heading: "Finishing Section",
      subtitle: "Iron, finish and reject tracking — ready for packing quantity",
      fromSewing: "সেলাই থেকে প্রাপ্ত",
      iron: "আয়রন",
      finish: "ফিনিশ",
      reject: "রিজেক্ট",
      readyForPacking: "প্যাকিংয়ের জন্য প্রস্তুত",
      totalReady: "মোট প্রস্তুত",
    },
    packing: {
      heading: "Packing Section",
      subtitle: "Carton packing, color/size breakdown and ready-to-ship quantity",
      color: "রং",
      size: "সাইজ",
      cartons: "কার্টন",
      packed: "প্যাকড",
      ready: "প্রস্তুত",
      totalCartons: "মোট কার্টন",
      totalPacked: "মোট প্যাকড",
    },
  },
};

export type BnDict = typeof bn;
